# Generated by Django 5.1.7 on 2025-03-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('consultant', 'Consultant')], default='nurse', max_length=20),
        ),
    ]
